// Expanded data with 32 emotion cards
export const simulatedEmotionData = [
  { emotion: "happiness", score: 0.85 },
  { emotion: "joy", score: 0.82 },
  { emotion: "excitement", score: 0.78 },
  { emotion: "contentment", score: 0.75 },
  { emotion: "amusement", score: 0.72 },
  { emotion: "love", score: 0.70 },
  { emotion: "pride", score: 0.67 },
  { emotion: "optimism", score: 0.65 },
  { emotion: "calmness", score: 0.63 },
  { emotion: "satisfaction", score: 0.60 },
  { emotion: "relief", score: 0.58 },
  { emotion: "interest", score: 0.55 },
  { emotion: "anticipation", score: 0.52 },
  { emotion: "surprise", score: 0.50 },
  { emotion: "nostalgia", score: 0.48 },
  { emotion: "hope", score: 0.45 },
  { emotion: "anxiety", score: 0.43 },
  { emotion: "confusion", score: 0.40 },
  { emotion: "doubt", score: 0.38 },
  { emotion: "boredom", score: 0.35 },
  { emotion: "sadness", score: 0.33 },
  { emotion: "disappointment", score: 0.30 },
  { emotion: "embarrassment", score: 0.28 },
  { emotion: "guilt", score: 0.25 },
  { emotion: "anger", score: 0.23 },
  { emotion: "frustration", score: 0.20 },
  { emotion: "disgust", score: 0.18 },
  { emotion: "fear", score: 0.15 },
];